### ISSUE TITLE
The new package

### ISSUE THREAD

**Issue by brgrz** [srkirkland/DataAnnotationsExtensions#68]
What's up with the new MVC package and how is it different to MVC3 (1.1.2) package? Which one should we use?

https://www.nuget.org/packages/DataAnnotationsExtensions.MVC/

**Comment by srkirkland** [comment]
@brgrz The MVC package 3.0.0 should be mostly the same as the MVC3 package you refer to, except I'm now explicitly depending on the MVC3 nuget package (since we are past the days of installing it into the GAC). I'm currently working on supporting MVC5 natively so the idea is that the MVC 5.0 package will be for ASPNET MVC version 5 and so forth.  I'd keep using the MVC3 package for now while I work out the kinks in the newer format.
