### ISSUE TITLE
[Date] works only with [string] type property.

### ISSUE THREAD

**Issue by gabrielius** [srkirkland/DataAnnotationsExtensions#70]
For me attribute [Date] works only with [string] type property.

**This fails:**
```
[Date(ErrorMessage="malformed date")]
public DateTime DesiredDate { get; set; }
```
**This works OK:**
```
[Date(ErrorMessage="malformed date")]
public string DesiredDate { get; set; }
```
Using `.NET Framework 4.5`, `MVC 5`. Any ideas?

**Comment by srkirkland** [comment]
@gabrielius 

tl;dr -- For DateTime properties the built-in MVC validation takes precedence.

ASP.NET MVC 5 basically hijacks the validation for the DateTime object because it has type checking support now.  So yea, if you use [Date] on a DateTime field then MVC knows what to do natively and thus this library just "gets out of the way" and does't attach the validator (it does on strings though of course as you've seen).
